### ISSUE TITLE
ロールオーバー時に親要素をはみ出した領域が隠れてしまう

### ISSUE THREAD

**Issue by kohta-okishima** [freecle-mate/mate#10]
こんな状態

<img width="1275" alt="2017-12-02 21 21 54" src="https://user-images.githubusercontent.com/1265649/33515451-1292e2b0-d7a7-11e7-909f-fffdb48ac965.png">

今はこの事象が発生するほど検索結果が少ない場合に空行を出力して回避している

**Comment by kohta-okishima** [comment]
現状これが原因で運用に支障が出ているわけではないので後回しでOKです(優先度一番低くてOK)。

この類のものにはnitsというタグをつけてます

**Comment by kohta-okishima** [comment]
@freecle-mate 

本件、下記キャプチャのように空行出力で全ステータス表示されるように対応(運用上支障がない)してありますのでご確認いただいて問題ないようであればクローズでお願いできますでしょうか？

<img width="1275" alt="2017-12-12 8 19 46" src="https://user-images.githubusercontent.com/1265649/33858995-4a7d6d24-df15-11e7-8dcd-80aabc7d82e9.png">

ステージングデプロイ済みです。

**Comment by freecle-mate** [comment]
チェックしました。問題ありません。

クローズはこちらで対応した方が良いですか？（念のため確認）
教えていただければ、沖島さんのやり方に合わせてこちらで対応します。

**Comment by kohta-okishima** [comment]
@freecle-mate 

ご確認ありがとうございます。

それでは以後、

Githubのissueはこちらで作ってるのでこちらでクローズ、
タスク管理表は貴社にて更新(DONE)でいかがでしょうか？

**Comment by freecle-mate** [comment]
@kohta-okishima 

タスク管理表をDONEに更新しました。
GithubのIssesクローズは沖島さんの方でお願いします。

**Comment by kohta-okishima** [comment]
@freecle-mate 

ありがとうございます。
本件クローズいたします。
