### ISSUE TITLE
質問フォームで特定の手順でhtml5のrequire属性が動作しなくなる

### ISSUE THREAD

**Issue by kohta-okishima** [freecle-mate/mate#11]
## 場所

質問フォーム(管理画面から質問リンク発行してエンドユーザがアクセスするとこ)

## 事前条件

回答待ちの質問があり、その設問として回答必須の質問(犬種 or 猫種)が設定されていること

## 再現手順

1. 何も入力しないで「投稿する」ボタンを押す
2. requiredのバリデーションに引っかかる
3. 必須の質問を入力する -> 入力したのにバリデーションに引っかかったまま

<img width="1280" alt="2017-12-02 22 25 30" src="https://user-images.githubusercontent.com/1265649/33516081-c60812fe-d7af-11e7-88cb-96482116927b.png">

**Comment by kohta-okishima** [comment]
インクリメンタルサーチを実装するために用いているselect2というライブラリが原因の模様

**Comment by hori-imuuzak** [comment]
再現手順確認済み
原因調査から

**Comment by kohta-okishima** [comment]
horiさんにはアプリの方に注力指定いただきたいので本件こちらで引き取ります。

**Comment by kohta-okishima** [comment]
ステージングQAへ

**Comment by freecle-mate** [comment]
Please Confirmを確認しました。
ステージング環境でバグ修正されているかチェックしましたが、

犬種・猫種に関する必須質問に対する入力がないまま「回答する」を選択すると、
その後、入力しても"この項目は必須入力です"というアラートがでて、
「回答する」ボタンを選択できません

![2017-12-11 18 15 19](https://user-images.githubusercontent.com/32240645/33823679-4894cad2-de9f-11e7-8c75-deff4998e87b.png)

**Comment by kohta-okishima** [comment]
本件まだステージングにデプロイしてないです。

まずこちらで確認しようかなと思って、ステージングQAへという書き方にしてました。加えて確認中のタグ自体がplease confirmタグしかなかったのでこれを使ってましたが、たしかにPleaseというprefixだと御社に頼んでいるニュアンスに見えるので以後きをつけます、。
失礼しました。

以後、御社に依頼するものは assigneeでfrrecle つけるか 「@freecle-mate 確認お願いします」と明示的にたのむ & Please Confirm タグつけるということにします。

せっかく確認して頂いたのに申し訳ないです。

**Comment by freecle-mate** [comment]
Pleaseと書いてあったので、確認した方が良いのかなと思い、先走りました。

>>以後、御社に依頼するものは assigneeでfrrecle つけるか 「@freecle-mate 確認お願いします」と
>>明示的にたのむ & Please Confirm タグつけるということにします。
承知いたしました。

**Comment by kohta-okishima** [comment]
@freecle-mate 

こちらコミットがステージングに反映され、こちらでの結合テストも済んでいるので貴社にてご確認いただいて結構です。
よろしくお願い致します。

**Comment by freecle-mate** [comment]
@kohta-okishima 
確認しました。問題ありません。
