### ISSUE TITLE
質問フォームのテスト

### ISSUE THREAD

**Issue by kohta-okishima** [freecle-mate/mate#12]
掲題の機能の動作確認をお願いします。

バグがあればご教示お願いします。
その際、可能であればGithubでイシューを作ってください。

e.g.
https://github.com/freecle-mate/mate/issues/11

## 場所

<img width="1275" alt="2017-12-03 8 47 32" src="https://user-images.githubusercontent.com/1265649/33520887-a1d893ca-d806-11e7-8f50-4c6419ab10fc.png">

https://prottapp.com/p/b847c9#/s/5a1be4d286e46502c8a3b6ed

加えて上記画面にてエンドユーザが発行したリンクへアクセスができて、質問に回答できること

## 注釈

以下を念頭にご確認お願いします。

```
>⑧質問依頼画面にリンク発行ボタン、クリアボタンが無い（prottには有）

リンク発行ボタンはあります。
最低限質問を公開できるデータを入力した上で更新ボタンを押してください。すると出ます。

これも仕様がわからなかったのでこちらで勝手に決めてますが、データフロー上最初からリンク発行ボタンを表示しておいてフォームが空の状態のままこのボタン押してもリンク発行できないのでこのようにしてます。
最初から出した方がよければその他データの状況に応じて各種のUIをどのように制御し、それに付随してエンティティの状態はどうなるのがいいかをドキュメントにまとめていただければその通り対応します。

クリアボタンやキャンセルボタンが色々なところにあるのですがこれも仕様が不明です。

後者はモーダル閉じる雰囲気でわかるものやそもそもprottで遷移自体が入ってるものもあって概ね問題ないのですが、フォームのクリアボタンは難解で、そもそもこれの振る舞いがフォームに入力されている項目を全て削除などの場合、誤クリックのリスクの方が高く必要なのか疑問なところです。
```

ref:
https://mate-freecle.slack.com/archives/C71PTP78E/p1512079034000361

### 現時点で発覚しているバグ

現時点で以下のバグがありますのでこれ以外に

https://github.com/freecle-mate/mate/issues/11

**Comment by kohta-okishima** [comment]
こちらで実施した結合テストでのチェックポイント

* ユーザリストで質問可能状態のユーザに対してのみこのフォームへのリンクを表示すること
* 質問依頼で画像が追加できること
* 質問依頼で動画が追加できること(拡張子mp4のみ対応)
* 質問依頼で質問が設定できること
* 「質問依頼を追加+」でフォームが非同期処理で追加されること
* 「更新」ボタンを押下で
  * プレビューが更新されること
  * 「リンクを発行」ボタンが表示されること
* エンドユーザが発行されたリンクにアクセスできること(前提条件: 未回答の質問がある)
* エンドユーザが質問に回答できること
* エンドユーザが回答した内容が正常に保存されること
* 全質問回答時にエンドユーザが「質問回答済み」状態に遷移すること
* 回答された質問は投稿状況一覧に「掲載OK」状態で表示されること

**Comment by kohta-okishima** [comment]
## 微妙な部分

>全質問回答時にエンドユーザが「質問回答済み」状態に遷移すること

質問が複数ある場合、ユーザが途中で回答をやめてしまった場合にずっと質問中状態のまま(= 新しく質問ができない。仕方がないか？)

**Comment by freecle-mate** [comment]
テスト完了しました。機能面でのバグはありませんでした。

**Comment by freecle-mate** [comment]
・質問を1/2回答している場合は回答したものだけは確認できること
　- 例えば、２つの投稿について質問し、その内１つの投稿のみ回答完了している場合は、
 　 その１つはコンテンツ一覧に表示できること
　- １つ目の投稿にQ1〜Q4あり、Q2の回答途中でユーザーが回答をやめてしまった場合は、
　　コンテンツ一覧には表示しない／できない

>>質問が複数ある場合、ユーザが途中で回答をやめてしまった場合にずっと質問中状態のまま(= 新しく質問ができない。仕方がないか？)
>>ただし回答された質問に関してはコンテンツ一覧に表示されて編集も可能。

**Comment by freecle-mate** [comment]
>>フォームのクリアボタンは難解で、そもそもこれの振る舞いがフォームに入力されている項目を全て削除などの場合、誤クリックのリスクの方が高く必要なのか疑問なところです。
必要です。誤クリックのリスクがあることも想定して、UIデザインしています。
クリアボタンを追加していただき、選択時に全項目を削除する仕様にして下さい。

>>データフロー上最初からリンク発行ボタンを表示しておいてフォームが空の状態のままこのボタン押してもリンク発行できないのでこのようにしてます。最初から出した方がよければその他データの状況に応じて各種のUIをどのように制御し、それに付随してエンティティの状態はどうなるのがいいかをドキュメントにまとめていただければその通り対応します。
最初からリンク発行ボタンがある場合、更新ボタン選択後にリンク発行ボタンが表示される場合の2つのUIを検討しました。大きな違いはない為、今のままでいきます。修正の必要ありません。

>>クリアボタンやキャンセルボタンが色々なところにあるのですがこれも仕様が不明です。
クリアボタンの仕様は以下とします。
　- ボタン選択時に、
　　　- 画像サムネイルを全て削除できること
　　　- 質問のジャンルと質問内容に入力している情報を全て削除できること
質問依頼リンク発行画面に、コピー／キャンセルボタンは表示していますが、それ以外、質問依頼画面にキャンセルボタンをもうけていません。再度、久保と確認しましたが、色々キャンセルボタンがあるこを確認できませんでした。

**Comment by kohta-okishima** [comment]
ご確認ありがとうございます。

>クリアボタンを追加していただき、選択時に全項目を削除する仕様にして下さい。

必要かどうか云々は僕の主観なので置いておいて、これ実装上フォームが分割されているのでクリアボタンを押してどういう振る舞いになるのか不明だったので作ってないというのが大きいです。
全項目とのことで画像も削除してしまうほうこうで承ります。

>最初からリンク発行ボタンがある場合、更新ボタン選択後にリンク発行ボタンが表示される場合の2つのUIを検討しました。大きな違いはない為、今のままでいきます。修正の必要ありません。

👍 :

>質問依頼リンク発行画面に、コピー／キャンセルボタンは表示していますが、それ以外、質問依頼画面にキャンセルボタンをもうけていません。再度、久保と確認しましたが、色々キャンセルボタンがあるこを確認できませんでした。

これは文脈的に管理画面の中でといういみですね。
実際に色々なところにありますしprottだけだと押したパターンの画面もないしどういう制御になるか不明じゃないですか？ということでした。
ご両人でのご確認までいただいたのにすみません。

単純な動作だったらいちいち画面まで作っていただかなくてもいいですけど、できれば何らかのドキュメントで説明があるのが望ましい部分ですね。じゃないと作り直したら時間浪費しますし、納品の時にもめるので。
今回はもうそこ気にしてたら進まないんでGitHubでこういう感じでやりましょう。

難所ですがバグは新しく出なかったのはよかったです。
今週中目処にクリアボタン追加でそれ以降貴社の出したいタイミングでリリースしましょう。

引き続きよろしくおねがいします。

**Comment by kohta-okishima** [comment]
@freecle-mate 

クリアボタンを実装し、ステージングにデプロイしました。
ご確認いただいて問題にようでしたらご教示お願いします。

**Comment by kohta-okishima** [comment]
こっちは検査入ってしまって問題ないです。

**Comment by freecle-mate** [comment]
テストしました。
クリアボタン選択後、以下の仕様が実装されていることを確認しました
　- 画像サムネイルを全て削除できること 　- 質問のジャンルと質問内容に入力している情報を全て削除できること

加えて、質問を1/2回答している場合は回答したものだけは投稿状況の確認に反映されることも確認しました
　- 例えば、2つの投稿について質問し、その内1つの投稿のみ回答完了している場合は、その1つはコンテンツ一覧に表示できること
　- 1つ目の投稿にQ1〜Q4あり、Q2の回答途中でユーザーが回答をやめてしまった場合は、コンテンツ一覧には表示しない／できない

以下、二点お願い致します。
①スマホでは質問に回答することができません。添付から他ページに遷移／スライドすることができません（must）
②質問依頼画面のQuestionアイコンのサイズを修正願います（nits）

![img_4610](https://user-images.githubusercontent.com/32240645/33825713-e732ddae-dea5-11e7-8fbc-6200ec558bd1.PNG)
![2017-12-11 18 56 11](https://user-images.githubusercontent.com/32240645/33825724-ec75a3d2-dea5-11e7-8549-b8341eb23a52.png)

**Comment by kohta-okishima** [comment]
>①スマホでは質問に回答することができません。画像添付。他ページに遷移／スライドすることができません、確認お願いします（must）

そもそもsupport request同じスライダを使ってますし何度も確認してるところなんでこれはないですね。

キャプチャ見た感じだとトップページにリダイレクトされているように思えるんですがすでに回答済みの質問や、存在しない短縮URLにアクセスしてないですかね？
(覚えてらっしゃると思いますが、後者はインスタのDMの対応でトップページへのリダイレクト処理を入れてます)

**Comment by kohta-okishima** [comment]
>②質問依頼画面のQuestionアイコンのサイズを修正してください（nits）

以前スマホでの解像度に相対的に対応する枠組みでvwのような単位をお話しさせていただきましたが、その兼ね合いからPCだとそういうアイコンになりますが、スマホではこんな感じで表示されます。

![image-1](https://user-images.githubusercontent.com/1265649/33827020-2c568e22-deaa-11e7-8bc1-24338496b622.jpeg)

<img width="1276" alt="2017-12-11 19 33 42" src="https://user-images.githubusercontent.com/1265649/33827036-40af6d26-deaa-11e7-8e98-cd40ecbb8696.png">

今スマホに関しては適切に相対値効いてると思ってたんですが、ここからさらに修正したほうがよろしいでしょうか？
修正する場合はもpxで固定してしまおうかと思ってます。

**Comment by freecle-mate** [comment]
スマホで再検証しました。問題なく利用できました。

先ほどのエラーは、PCでQ1〜2の質問を途中まで回答したリンクを、再度スマホで表示した際にでたものでした。失礼いたしました。

Questionのアイコンサイズの件、スマホでも再確認しました。PCだとかなり大きいですが、スマホだと問題ないですね。本件、DONEにしましょう👌

**Comment by kohta-okishima** [comment]
早速ご確認ありがとうございます。
引き続き他の課題もクリアしていきます。

**Comment by kohta-okishima** [comment]
管理表DONEにしていただいてるのでこちらもクローズ
