### ISSUE TITLE
ユーザリストのスタイル調整

### ISSUE THREAD

**Issue by kohta-okishima** [freecle-mate/mate#13]
掲題の件のご対応をお願いします。

## 画面

https://prottapp.com/p/b847c9#/s/5a1be4d14942fb3fec2a11aa

## お願いしたいこと

prottと差異がある箇所の修正。
prottと突き合わせて自身の判断で実施していただきたいですが、こちらで気にしていることは以下です。

* ページングのスタイル
  * ページングのViewはapp/views/kaminari になりますが読めないなら後回しにしてください
  * ページングのスタイルは全ページ共通です
* 検索のテキストフィールドのプレースホルダーに虫眼鏡のアイコンがない

**Comment by hori-imuuzak** [comment]
- [ ] 左端、アイコンを少し大きくする
- [ ]  ユーザーアイコンのオンライン表示をなくす
- [ ] 表の見出し文字寄せをprottに合わせる
- [ ] テキスト検索に検索アイコンを表示する
- [ ] テキスト検索のボックスを少し広くする

**Comment by kohta-okishima** [comment]
ref: https://github.com/freecle-mate/mate/issues/45
