### ISSUE TITLE
アカウント管理のスタイル調整

### ISSUE THREAD

**Issue by kohta-okishima** [freecle-mate/mate#14]
掲題の件のご対応をお願いします。

## 画面

index
https://prottapp.com/p/b847c9#/s/5a1be4d14942fb0d052a15f9

パスワード変更モーダル
https://prottapp.com/p/b847c9#/s/5a1be4d186e4651b6da3b6d0

## お願いしたいこと

prottと差異がある箇所の修正。
prottと突き合わせて自身の判断で実施していただきたいですが、こちらで気にしていることは以下です。

* index
- [x]  * 「パスワードの再設定」のalignment
- [x]  * 上記列のアイコンが若干prottと違う(font awesomeから探し出せなかった)
- [x]  * モーダルのスタイル全般

**Comment by hori-imuuzak** [comment]
チュートリアル的に対応してみました。

モーダルスタイル全般というのはパスワード再設定に関わらず、全モーダルを対象としてissueとしていますか？
（そうであれば今回はパスワード再設定モーダルだけ対応しちゃいましたので、別途全modal対象で対応します）

**Comment by freecle-mate** [comment]
>>モーダルスタイル全般というのはパスワード再設定に関わらず、全モーダルを対象としてissueとしていますか？
#14 Issuesについては、パスワード再設定のモーダル修正だけで大丈夫です。

**Comment by hori-imuuzak** [comment]
ヘッダー文字サイズを合わせる

**Comment by hori-imuuzak** [comment]
ユーザーID => 管理者ID に文言変更

**Comment by kohta-okishima** [comment]
ref: https://github.com/freecle-mate/mate/issues/56
