### ISSUE TITLE
管理者編集フォームのスタイル修正

### ISSUE THREAD

**Issue by kohta-okishima** [freecle-mate/mate#15]
掲題の件のご対応をお願いします。

## 画面

<img width="1275" alt="2017-12-03 16 18 05" src="https://user-images.githubusercontent.com/1265649/33523274-ad195de8-d845-11e7-8fd0-2128aa0145f9.png">

prottが見当たらないのでキャプチャで

## お願いしたいこと

スタイルを抜本的になおしたフェーズ以降、いつのまにかフォームの各要素がコンテナの最大幅をはみ出してラベルなどが読み取れなくなりました。
prottがないので細かいところは割愛して大丈夫ですが、文字が見れるようになるなどの最低限のレイアウト修正をお願いしたいです。

**Comment by hori-imuuzak** [comment]
ユーザーID -> 管理者ID に文言変更

**Comment by kohta-okishima** [comment]
ref: https://github.com/freecle-mate/mate/issues/56
