### ISSUE TITLE
実績の算出画面のスタイル調整

### ISSUE THREAD

**Issue by kohta-okishima** [freecle-mate/mate#16]
掲題の件のご対応をお願いします。

## 画面

https://prottapp.com/p/b847c9#/s/5a1be4d186e4657a5ba3c124

## お願いしたいこと

prottと差異がある箇所の修正。
prottと突き合わせて自身の判断で実施していただきたいですが、こちらで気にしていることは以下です。

* 日付入力のコントロールでのプレイスホルダーがprottと違う
※ そもそもinput type=date でできるのか不明なのでできないなら「これはHTML5の仕様上できません」というアンサーを関口さんにしていただく形でOKです

**Comment by hori-imuuzak** [comment]
アカウント名

下の `名前` は `ID` に文言変更

**Comment by hori-imuuzak** [comment]
カレンダーのプレースホルダーは現状のままでOK

**Comment by kohta-okishima** [comment]
対応済み
