### ISSUE TITLE
権限関連

### ISSUE THREAD

**Issue by kohta-okishima** [freecle-mate/mate#18]
* アルバイトが質問リンク発行オペレーションを行えるように改修必要

**Comment by kohta-okishima** [comment]
@freecle-mate 

一旦

アルバイトA: 自分が登録したユーザのみ質問可能
アルバイトB: 全ユーザに対して質問可能

でよろしいでしょうか？

**Comment by freecle-mate** [comment]
@kohta-okishima 

仕様は現本番環境のユーザーリスト表示条件同様に、以下でお願いいたします。

アルバイトA：自分が登録したユーザのみ質問可能
アルバイトB：全ユーザに対して質問可能

**Comment by kohta-okishima** [comment]
ご教示ありがとうございます。
ユーザー表記についても諸々承知致しました。

Viewでつい癖でユーザと書かないよう以後気をつけます。

**Comment by freecle-mate** [comment]
@kohta-okishima 
権限について、仕様を細かくテキスト化しました。
ステージングに既に反映されている項目は（DONE）、それ以外を（未着手）と定義しました。
未着手についてはScope Inでご対応いただきたく、宜しくお願い致します。

■アルバイトA
・表示画面：
　- ユーザーリスト（DONE）

・ユーザーリスト：
　- 自分でユーザー登録した人のみリスト表示（DONE）
　- 自分でユーザー登録した人には質問依頼可能（未着手）
　- ステータス変更不可能（DONE）

■アルバイトB
・表示画面：
　- ユーザーリスト（DONE）
　- 投稿状況の確認（未着手）
　- ハッシュタグの確認（DONE）

・ユーザーリスト：
　- 自分で登録した人以外のリストも表示（DONE）
　- ステータス変更不可能（未着手）
　- 質問依頼可能（DONE）

・投稿状況の確認
　- 全機能の利用権限付与（未着手）

・ハッシュタグの確認
　- 全機能の利用権限付与（DONE）

**Comment by kohta-okishima** [comment]
@freecle-mate 

こちらも対応完了しステージング反映済みなのでご確認いただいて問題ありません。

**Comment by freecle-mate** [comment]
チェックしました。バッチリです！
問題ありません。本件、DONEにしましょう。
