### ISSUE TITLE
ユーザーリストに削除機能追加

### ISSUE THREAD

**Issue by freecle-mate** [freecle-mate/mate#20]
アルバイトのご操作が多い為、ユーザーリストを手動で削除できる機能を追加します

■前提
・アルバイトは削除機能を利用することができない／freecleのみに利用権を付与する
・ユーザーリストを削除しても、サポーター依頼数の実績を減らすことはできない
　　→ データ連携の追加開発が必要になる為、オペレーションでカバーする
　　→ 具体的には、アルバイトに誤操作を申告して頂き、サポーター依頼数の実績からその分を差し引く

■prott
・現在作成中

■ユースケース
・ユーザーリストの表の一番右にある3つボタン押下
・ユーザー情報の編集、削除の2択の内、削除機能を選択
・モーダルがでる（タイトルはユーザー削除）
・削除、キャンセルの2択の内、削除を選択
・ユーザーリストのページに戻る、上部に「ユーザーを削除しました。」というメッセージ表示

**Comment by kohta-okishima** [comment]
🙆‍♂️

**Comment by freecle-mate** [comment]
@kohta-okishima 
prottに反映しました
https://prottapp.com/p/b847c9#/s/5a24eeaa86e465740def6081

**Comment by kohta-okishima** [comment]
ref: https://github.com/freecle-mate/mate/issues/45

上記で対応の確認依頼中
