### ISSUE TITLE
質問テンプレート追加

### ISSUE THREAD

**Issue by freecle-mate** [freecle-mate/mate#22]
犬種、ブリーダー、ファッション以外の質問テンプレートをシステムに実装する。

スピード優先で上記のテンプレートのみ作成し、実装していただきましたが、
開発依頼時の要件定義に記載していた通り、以下4つのテンプレートも追加したいと考えています。
　- ヘアスタイル
　- フード
　- オモチャ
　- ヘルスケア

上記、久保が作成し、別途テンプレート共有します。

**Comment by kohta-okishima** [comment]
🙆‍♂️

**Comment by freecle-mate** [comment]
質問テンプレートを更新しました。
エクセルのA列＆B列をご確認の上、システム反映してください。
https://docs.google.com/a/freecle.co.jp/spreadsheets/d/1bYYwAWCxi1LGvlUJj3Fhl963GhkSXWvUbJIxrQKNbJ4/edit?usp=sharing

加えて、当初予定していた選択式回答はScope Outにしましょう。
その結果、以下の文面の変更も必要です。ご対応ください。

■ファッション
As-Is：どのくらいの価格で購入されましたか。差し支えなければ、価格帯をお選びください。
To-Be：どのくらいの価格で購入されましたか。

■ブリーダー
As-Is：問い合わせ対応方法をお選びください。
To-Be：削除

As-Is：お電話での問い合わせをご希望される方は、お電話番号を教えてください。
To-Be：削除

**Comment by kohta-okishima** [comment]
@freecle-mate 

こちら対応の上ステージングデプロイ完了しました。

**Comment by freecle-mate** [comment]
@kohta-okishima
