### ISSUE TITLE
ローカル環境でのユーザー追加・ログインまでのオペレーションを教えてください

### ISSUE THREAD

**Issue by hori-imuuzak** [freecle-mate/mate#23]

**Comment by kohta-okishima** [comment]
ログインという文脈からユーザというのが管理者のことだと思うんですが、最初はrails consoleで作成したください。
もしかしたらrake db:seed_fuで入ったかも・…

**Comment by kohta-okishima** [comment]
適切に環境変数設定してあればしょうきrakeタスクで以下が入るので一旦これを使ってください。

https://github.com/freecle-mate/mate/blob/master/db/fixtures/development/admins.rb

**Comment by hori-imuuzak** [comment]
あざます。確認しますね。

**Comment by hori-imuuzak** [comment]
ログインできたのでクローズします
