### ISSUE TITLE
http://localhost:3000/admin/users でページが開かない

### ISSUE THREAD

**Issue by hori-imuuzak** [freecle-mate/mate#24]
id: dev
pw: 20170920
ログイン後

admin/xxx 系の画面で起きます

<img width="655" alt="localhost 2017-12-07 08-38-05" src="https://user-images.githubusercontent.com/26102225/33691102-fc140380-db29-11e7-9ee9-df895b48f6a3.png">

**Comment by kohta-okishima** [comment]
rackサーバのログがないので何が起こってるのかわからないですが権限関係だと思うので admin.manager? がtrue になるように権限設定してください。

**Comment by hori-imuuzak** [comment]
おお、いけました。ありがとうございました。
