### ISSUE TITLE
コンテンツリスト項目のスタイル調整

### ISSUE THREAD

**Issue by hori-imuuzak** [freecle-mate/mate#28]

**Comment by hori-imuuzak** [comment]
![development mate dev 2017-12-10 13-12-29](https://user-images.githubusercontent.com/26102225/33801851-d9116e0c-ddab-11e7-8d93-3aa3d4e4d2ab.png)

**Comment by hori-imuuzak** [comment]
[掲載OK」の文言はDB文言なので、seed調整してもらう必要がありそう

**Comment by hori-imuuzak** [comment]
投稿状況のスタイル調整（ユーザーリストのステータスに合わせる）

**Comment by hori-imuuzak** [comment]
いいね数、クリック数にそーとアイコン追加

**Comment by hori-imuuzak** [comment]
広告は一種類のみ（クリック数）

**Comment by hori-imuuzak** [comment]
prottを正としてスタイル調整する

**Comment by kohta-okishima** [comment]
ref: https://github.com/freecle-mate/mate/issues/38
