### ISSUE TITLE
ダッシュボードのグラフのスタイル定義

### ISSUE THREAD

**Issue by hori-imuuzak** [freecle-mate/mate#29]
ライブラリでどこまでできるか調査から

**Comment by kohta-okishima** [comment]
堀さん自体もういないのでクローズ。

調査の件は、グラフ自体ライブラリで出力しているのでかなり細かくスタイル調整したいならフルスタックでグラフ生成処理を実装するしかありません。
それかライブラリでテーマを適用できるものを探して、テーマを実装するかでこれに関してはコード追加はなく完全にデザインの領域です。
