### ISSUE TITLE
Webアプリ Viewコンポーネント実装

### ISSUE THREAD

**Issue by freecle-mate** [freecle-mate/mate#30]
React NativeでViewコンポーネントを実装する作業を堀さんにお願いします。

**Comment by hori-imuuzak** [comment]
あ、ちなみにwebとネイティブアプリ（もし進んでいたら）でそれぞれ進捗状況をお伺いできると幸いです。

**Comment by freecle-mate** [comment]
@kohta-okishima 
既に着手していらっしゃったら教えて下さい。
React NativeでViewコンポーネントを実装する作業は堀さんにお願いします。

**Comment by kohta-okishima** [comment]
horiさん自体もうチームからいなくなっちゃったんでクローズしました。
