### ISSUE TITLE
堀さんローカル環境での作業をステージングへ反映する方法

### ISSUE THREAD

**Issue by freecle-mate** [freecle-mate/mate#31]
@kohta-okishima 
本日、堀さんとMTG実施しました。
フォントや表のサイズ修正等、細かく対応してくださっています。
ステージング環境にはどのように反映すれば良いですか？
パラレルで作業しているので、デジャブがおきないように沖島さんの考えを確認しておきたいです。

**Comment by kohta-okishima** [comment]
デプロイにはcapistranoというデファクトなデプロイツールを使っていて、設定も済んでるので秘密鍵さえあれば `cap staging deploy `みたいに実行可能です。

なので今後はhoriさんに秘密鍵を渡す・デプロイが必要なら上記コマンドで実行する

でよろしいかと思います。

なので、

* horiさんに鍵渡す
* capコマンドで動作確認

で解決です。

あと、今は大丈夫ですが、できればhoriさんがテクニカルサイドのメインとなる段階で僕が持ってる鍵は無効化してください(セキュリティ上の兼ね合い)。
