### ISSUE TITLE
投稿状況の確認 受入検査依頼

### ISSUE THREAD

**Issue by kohta-okishima** [freecle-mate/mate#38]
貴社にて作成していただいた mateタスク管理表 の下記課題への対応を行いました。

```
## 投稿状況の確認

広告機能の開発

prottデザイン反映（フォント・アイコンの位置等）

"承認状況のステータスの文字修正
　- 掲載OK→公開済み／非公開の2択　→DB文言なので別途対応"

リンク切れ通知機能の開発（iマーク）

投稿状況のフィルタリング機能の開発（非公開／公開済み）

"コンテンツ編集画面の文字修正
　- 掲載OK→公開済み　→DB文言なので別途対応
　- 質問依頼→コンテンツ情報
　- (100字以内)→＜100字以内＞
　- (10個以内)→＜10個以内＞"
horiさんが対応済み

新規コンテンツの投稿機能開発／表右のダイヤルマーク選択

"プロユーザー用の新規コンテンツ投稿機能開発
　- 画像・広告追加機能
　- ユーザー名の選択機能（プロユーザー登録者のみ反映）
　- ユーザーリスト登録ID以外のユーザ名ははじく仕様実装"
```

ステージングデプロイ済みです。

>　- 掲載OK→公開済み／非公開の2択　→DB文言なので別途対応"
> リンク切れ画面の開発（iマーク選択後／詳細はprottに反映）

今後質問回答後に遷移するステータスは非公開にしました。今後掲載OKは使われなくなります。

よろしくお願い致します。

**Comment by kohta-okishima** [comment]
デプロイタイミングの都合で

```
新規コンテンツの投稿機能開発／表右のダイヤルマーク選択

"プロユーザー用の新規コンテンツ投稿機能開発
　- 画像・広告追加機能
　- ユーザー名の選択機能（プロユーザー登録者のみ反映）
　- ユーザーリスト登録ID以外のユーザ名ははじく仕様実装"
```

もステージングに入ってますが、これはまだこちらでの確認が不十分であるため一旦stayでお願いします。

**Comment by kohta-okishima** [comment]
```
新規コンテンツの投稿機能開発／表右のダイヤルマーク選択

"プロユーザー用の新規コンテンツ投稿機能開発
　- 画像・広告追加機能
　- ユーザー名の選択機能（プロユーザー登録者のみ反映）
　- ユーザーリスト登録ID以外のユーザ名ははじく仕様実装"
```

上記も確認したのでこちらも貴社での検査開始いただいて構いません。

一応トップコメントも更新しておきます。

**Comment by freecle-mate** [comment]
@kohta-okishima 
更新していただいた点、確認しました。
いくつか質問させてください。

①承認状況ステータス
掲載OKを「公開済み」に文字修正するという認識でしたが、掲載中という言葉にされたのはなぜですか？
些末なミスですが、できればお願いした通りに対応していただきたいです。

②検索ボックス
ユーザー名検索がユーザ検索になっています。文字修正お願いします。
加えて、ユーザー名検索とハッシュタグ検索のボックスの縦の長さを合わせてください。

③投稿機能
タイトルとハッシュタグを入力して更新ボタンを押しても、その後、何も起きません。
つまり、コンテンツを投稿できません。
沖島さんは出来てらっしゃるので、私の操作ミスですかね？ 教えてください。

④広告機能
広告編集のボックス・ボタンが表示されていません。
新規広告コンテンツの投稿画面も同様の状態です。

※以下の項目は問題ありません。Doneにしましょう。

・リンク切れ通知機能の開発（iマーク）
・投稿状況のフィルタリング機能の開発（非公開／公開済み）
・コンテンツ編集画面の文字修正
　- 質問依頼→コンテンツ情報
　- (100字以内)→＜100字以内＞
　- (10個以内)→＜10個以内＞"
・プロユーザー用の新規コンテンツ投稿機能開発
　- ユーザー名の選択機能（プロユーザー登録者のみ反映）
　- ユーザーリスト登録ID以外のユーザ名ははじく仕様実装

**Comment by kohta-okishima** [comment]
>①承認状況ステータス
>掲載OKを「公開済み」に文字修正するという認識でしたが、掲載中という言葉にされたのはなぜですか？

なぜですか？と言われましても別に故意に直してないわけじゃないですしただの修正漏れとしか答えようがないです。

MTG のときもprottにないステータスがあるみたいな指摘ありましたが、そもそも実装レベルで投稿のステータスを定義したのが9/21なのでその際にまだprottが間に合っていなかったのでこちらで定義したものが残ったのではないかと思いますので、こちらが貴社の意図に反してわざとこの文言にしているわけではないことをまず認識してください。

文言以前にステータスは基本設計段階で状態遷移条件や必要な制御の定義が必要だと思うのですが、プログラマがその粒度で考えている時点で工程に区分が破綻してますし、実装の立場だと制御を確認する方が遥かに重労働なので文言に気が回らないぐらいはご容赦いただきたいです。
そもそもprottにあるステータスだけだと実装自体が進められないのでこちらで考えてます。

反復1回目もしくは最初の実装の段階でこの類のミスをなくしたいというなら、こういうことを防ぐために通常はステータス一覧や状態遷移図があるので細かくこだわられるならまずはそういうドキュメントを用意されるといいのではないかと思いました。

>②検索ボックス
>加えて、ユーザー名検索とハッシュタグ検索のボックスの縦の長さを合わせてください。

ハッシュタグの方はライブラリの仕様上heightを編集するとおかしな挙動になりそうなので、ユーザー名検索の方を高くする方式でいきますがその点だけご承知おきいただければ幸いです。

> ③投稿機能
>タイトルとハッシュタグを入力して更新ボタンを押しても、その後、何も起きません。

こちらでソースを読みながら管理者の権限などを考慮したりして探索型で検査しましたが特に更新ができないということはありませんでした。
ステージングは矛盾したデータ構造が残ってるので古いデータを編集するとおかしな挙動になるかもしれないのでその辺も探しましたが、そもそもそういったデータは一覧に表示されなくなってますし、URL直入力でもフォームがおかしくなってるものは発見できませんでした。

お手数ですが 画面名(URL)、再現手順、実行環境(PC,スマホ OS上で起動しているブラウザ)などをご教示お願いします。

また、蛇足ですが現時点でプレビュー(画面サンプル)は動いてないので質問フォームみたいにプレビューに反映されない = バグと認識されないようにお願いします。
プレビューにはWebアプリのURLを入れますがそれがまだないためです。Webアプリ実装後に管理画面のiframeにURLを指定するだけで動くようになるのでその部分は後任の担当者に依頼をお願いします。

>④広告機能
> 広告編集のボックス・ボタンが表示されていません。

そもそもこの項目がないとフォームが送信できないので 3 の問題との絡みがあるかもしれないですがこちらでは特に再現できませんでした。

> 新規広告コンテンツの投稿画面も同様の状態です。

下図のURLのことをおっしゃているのかと思いますがこちらでは特にコントロールが非表示ということもありませんでした。

<img width="1275" alt="2017-12-18 6 57 09" src="https://user-images.githubusercontent.com/1265649/34084283-bf3ed90e-e3c0-11e7-879e-cfac264480e5.png">

なお、3,4に関してはChrome, Firefox , Safariで確認しました。

**Comment by freecle-mate** [comment]
@kohta-okishima 
Google Chromeの拡張機能「Adblock Plus」を削除したら、使えるようになりました。
お騒がせしました！

広告機能を確認しました。
添付のように記入し、更新ボタンを押しても、非公開を公開に変更することができません。
そもそも沖島さんのスクリーンキャプチャには更新ではなく、
作成というボタンになっているので私の環境の問題ですかね？
![2017-12-18 20 21 52](https://user-images.githubusercontent.com/32240645/34103803-768b39f2-e431-11e7-853c-86e68f0438bb.png)
![2017-12-18 20 21 56](https://user-images.githubusercontent.com/32240645/34103804-76bc4290-e431-11e7-9b19-21899c371f48.png)

**Comment by kohta-okishima** [comment]
@freecle-mate 

URLが

https://www.amazon.co.jp/Jeerui-Jeerui%C2%AE-%E3%83%9A%E3%83%83%E3%83%88%E7%94%A8-%E7%8A%AC%E7%94%A8-%E9%81%8B%E5%8B%95-%E7%8A%AC%E7%94%A8%E6%9C%8D-%E3%83%81%E3%83%A8%E3%83%84%E3%82%AD-%E3%82%B9%E3%83%9D%E3%83%BC%E3%83%84%E3%83%AF%E3%83%B3%E3%81%A1%E3%82%83%E3%82%93%E7%94%A8-%E3%82%B8%E3%83%A3%E3%82%B1%E3%83%83%E3%83%88-%E6%98%A5%E7%A7%8B%E5%86%AC-%E4%BF%9D%E6%B8%A9-%E9%98%B2%E5%AF%92-%E9%9B%A8-%E6%95%A3%E6%AD%A9-%E9%98%B2%E6%B0%B4-%E6%9A%96%E3%81%8B%E3%81%84-%E3%81%8D%E3%82%8A%E3%82%82%E3%81%AE-%E9%98%B2%E6%B0%B4%E3%82%B3%E3%83%BC%E3%83%88-%E3%83%9A%E3%83%83%E3%83%88%E7%94%A8%E5%93%81/dp/B0759KVPX5/ref=sr_1_2_sspa?ie=UTF8&qid=1513594961&sr=8-2-spons&keywords=%E3%83%9A%E3%83%83%E3%83%88&psc=1

みたいに想定外に長いのでエラーになってます。
データベースのカラムのデータ型変えて対応します。

なお、作成というボタンのものは新規コンテンツで、更新が既存コンテンツへの編集です。
基本この画面はフォーム送信や画像の追加などは非同期処理ですが前者はID確定させるとき(=作成ボタン押すとき)だけページ再読み込みが発生します。
URL変わるのとDOMの差分が多すぎるのでここまで無理やり非同期処理にしたらバグの温床になるのでこの点だけご承知おきいただければ幸いです。

**Comment by kohta-okishima** [comment]
@freecle-mate 

ご指摘いただいた課題を修正し、ステージングにデプロイしました。
お手隙の際にでもご確認頂ければ幸いです。

**Comment by freecle-mate** [comment]
@kohta-okishima 

遅くなりました。確認しました。
問題ないです。本件、Doneにしましょう！

**Comment by kohta-okishima** [comment]
@freecle-mate 

ご確認ありがとうございます。
本issueはクローズします。
