### ISSUE TITLE
ユーザーリスト 受入検査依頼

### ISSUE THREAD

**Issue by kohta-okishima** [freecle-mate/mate#45]
```
## トップページ

左のタブ（カラム）のサイズ修正
※サイドバーのwidthのことだと思いますが、horiさんが対応済みです(改修以後prott に近い幅になってる)

## ユーザーリスト

prottデザイン反映（フォント・アイコンの位置等）

承認状況一覧確認リストを承認状況確認リストに文字修正

"右上のダイヤルに表示される文字修正
　- ユーザーを登録→SNSユーザー登録
　- プロユーザーを登録→外部ユーザー登録"
※horiさん対応済み

"ユーザー登録画面のユーザー情報の右寄りアイコンの文字修正
　- ユーザー→属性"

"プロユーザー登録画面のプロユーザー情報の右寄りアイコンの文字修正
　- ユーザー→属性"

"ユーザーリストの表の一番右にある3つボタン押下後の画面修正
　- アイコンサイズ調整（更に大きくする）"

削除機能を追加
※投稿状況の確認でも当該ユーザーの投稿は消えます
```

**Comment by kohta-okishima** [comment]
@freecle-mate 

トップコメントに記載した課題をステージングデプロイしました。

>削除機能を追加

ドロップダウンメニューですが、テーブルの一番下でクリックした際

<img width="1274" alt="2017-12-14 10 57 07" src="https://user-images.githubusercontent.com/1265649/33974577-9029238c-e0cc-11e7-80c0-583ec9988253.png">

のようになりますが、スクロールすれば

<img width="1275" alt="2017-12-14 10 56 57" src="https://user-images.githubusercontent.com/1265649/33974589-9ae0ced8-e0cc-11e7-80e6-c586d45c1594.png">

このように表示はされるのでこの点注釈として申し上げておきます。

よろしくお願い致します。

**Comment by freecle-mate** [comment]
@kohta-okishima 
確認しました。問題ありません。
ドロップダウンメニューの表示方法、注釈していただきありがとうございます。確認し易かったです。
