### ISSUE TITLE
InstagramIDのバリデーションを実装

### ISSUE THREAD

**Issue by kohta-okishima** [freecle-mate/mate#5]
## ref

https://mate-freecle.slack.com/archives/C71PTP78E/p1512202445000046

最低限スペースは弾く

**Comment by kohta-okishima** [comment]
アルファベット・数字・ピリオド・アンダースコアだけで構成されてなかったらエラーにしました。
ステージングにデプロイしましたのでご確認お願いいたします。
@freecle-mate

**Comment by freecle-mate** [comment]
いくつかのパターンで検証し、「ご入力いただいたInstagram IDの書式が不正です。」を確認しました。問題ありません。

**Comment by kohta-okishima** [comment]
@freecle-mate 

早速ありがとうございます。
では本イシューはクローズさせていただきます。
