### ISSUE TITLE
検索ワードを記録するテーブル開発

### ISSUE THREAD

**Issue by kohta-okishima** [freecle-mate/mate#52]

**Comment by kohta-okishima** [comment]
@freecle-mate 
掲題の件、タスク管理表にあったので対応しておきました。

お打ち合わせの際に久保さんに対してこの検索ワード云々に関する機能への対応を固辞したのは、この類のものを都度受け入れていたら今までのように対応事項が際限なく増えていき、当初の見積もりの破綻と単価低下に拍車がかかってしまうので、納品の線引きがようやくなされた今では特に避けたいという意図がこちらとしてはありました。

今回に関しても具体的にどう言った形で記録するのか(キーワード自体を記録するのか、タグのIDを外部キーとして持つのか)、後者の場合存在しないキーワードは無視していいのか、タグの名前が変わったときどうすればいいのか、作った後別機能への組み込みをどうするかなどなど、対話を重ねるうちに対応範囲が広がっていくことが容易に想像できます
(こういったことを防ぐために設計が重要視されていて、設計にも基本設計や詳細設計などのフェーズがあり、その伝達手段としてドキュメントや課題管理ツールなどのコミュニケーションツールが付随するというのが自分の認識で、アジャイル開発というのはそれらを軽視するものではないと僕は思っています)。

実装自体はMTGの時にフリーキーワードではなく存在するタグでしか探せない仕様と伺ってますので、タグの外部キー(ID:1など)を保持する形式で実施してます。
まずいようであればテーブルの開発という範疇でのみ修正は承りますが、この類のものは一旦本件にて締め切らせていただければと思っています。

このような事柄自体、常識的なことであったり、暗黙的に遵守が前提であったりするので皆まで言ってはいけない事といいますか、言語化して通達すること自体かなり失礼だと思うので今まで言いませんでしたが、契約上の線引きのための相互理解として必要な情報だと思うので今回は忌憚なき意見としてお送りします。
恐れ入りますがご確認いただければ幸いです。

よろしくお願い致します。

**Comment by kohta-okishima** [comment]
ああ、勢いでPlease confirmタグつけちゃいましたけど動作確認できるようなものじゃないので一旦ER図で見ていただいたほうがいいですね。
ER図の方はもう少々お待ちください。

**Comment by freecle-mate** [comment]
@kohta-okishima 
ありがとうございます。

>>実装自体はMTGの時にフリーキーワードではなく存在するタグでしか探せない仕様と
>>伺ってますので、タグの外部キー(ID:1など)を保持する形式で実施してます。
上記ご認識通りです。問題ありません。

>>ああ、勢いでPlease confirmタグつけちゃいましたけど動作確認できるようなものじゃないので
>>一旦ER図で見ていただいたほうがいいですね。
上記の説明だけで十分ですし、沖島さんを信頼しているので、本件Doneにしましょう。
追加の開発が必要になった場合は次フェーズ以降相談します。
