### ISSUE TITLE
ハッシュタグの確認 受入検査依頼

### ISSUE THREAD

**Issue by kohta-okishima** [freecle-mate/mate#54]
```
新規タグの作成（＋ボタン）をモーダルに修正

"ハッシュタグの名称変更できる機能追加
　- #Tag-1をクリックすると、Renameできること
　- Rename後、Enterを押すと更新できること"

総ハッシュタグ数のカウント機能追加
```

**Comment by kohta-okishima** [comment]
@freecle-mate 
上記完了したのでご確認お願い致します。ステージングデプロイ済みです。

**Comment by freecle-mate** [comment]
@kohta-okishima 
確認しました。問題ありません。

ハッシュタグをRenameした後に、公開済みのコンテンツの投稿に紐付くタグの名前も
更新されるのか気になっていたのですが、問題ないですね。
加えて、新規ハッシュタグを作る際に既存のタグがでてくる仕様にしていただいたことも、
確認しました。ありがとうございます。

本件、Doneにしましょう。
