### ISSUE TITLE
ダッシュボード実装

### ISSUE THREAD

**Issue by freecle-mate** [freecle-mate/mate#58]
@kohta-okishima 
prottを更新しました。
https://prottapp.com/p/b847c9
以下、細かい要件です。ご確認の上、実装願います。

■折れ線グラフの横軸
・折れ線グラフのデフォルトは日別でお願いします
・日別の表示は、直近の10日-30日間でお願いします。使用スタイルの定義に合わせていただいて構いません
・日付の表記について、日別は12/16（MM/DD）でお願いします
・週別の表示は、直近の4週間でお願いします
・日付の表記について、週別は2017/12/18（YY/MM/DD）でお願いします。DDは月曜の日にちでお願いします
・月別の表示は、直近の12ヶ月間でお願いします
・日付の表記について、月別は2017/12（YY/MM）でお願いします
・年別の表示は、直近の5年間でお願いします
・日付の表記について、年別は2017（YY）でお願いします

■年齢層別
・折れ線グラフのデフォルトはALLでお願いします
・年齢層別のカテゴリは7つでお願いします（ALL／10代／20代／30代／40代／50代／60代）

■性別
・折れ線グラフのデフォルトはALLでお願いします
・ALL選択時は、男性＋女性ユーザーの登録数を表示してください
・男性選択時は、男性ユーザーの登録数だけ表示してください
・女性選択時は、女性ユーザーの登録数だけ表示してください

**Comment by kohta-okishima** [comment]
@freecle-mate 

prott拝見しました。

円グラフの真ん中に合計数出してると思うんですけど、ライブラリのソースコード読みましたがこういうレイアウトにはできないです。

貴社的にはソースどうこう言われてもイメージがわかないと思うのでライブラリが生成するイメージは以下をご覧ください。
https://www.chartkick.com/

辛うじて配色に関してはなんとかなりそうなのでprottと全く同色にしたいのであればお手数ですがカラーコードを16進数のRGBでお送りいただきたいです。
(e.g. サポーター構成-> ブリーダー: #ff0000)

基本prott似合わせる最大限の努力はしますが、以前どこかで書いたように細部までこだわろうとするとフルスクラッチでCSSやグラフ描画を実装しなければならなくてライブラリを使う意味がなくなりますし、
それか細かくスタイルをテーマとして指定できるライブラリを探してテーマを実装という運びになってしまい、それだともはやデザイナーの作業領域になってしまうのでこの辺こだわられるようなら後任の方に依頼してください。

そういう対応されるとしても僕がこれから作る集計のコアロジックがあれば改修はViewレイヤーだけで済むとは思いますので、その辺は責任持ってやらせていただきますが、前述したような点はご容赦いただければ幸いです。

**Comment by kohta-okishima** [comment]
@freecle-mate 

サポーターに関する統計の部分で「一般ユーザー」という区分がありこれが何のことかわからないのですが、

<img width="1277" alt="2017-12-18 13 48 32" src="https://user-images.githubusercontent.com/1265649/34090439-5b88be9a-e3fa-11e7-80c7-f5e62bbd419b.png">

上図で選択されているものという認識でよろしいでしょうか？

**Comment by freecle-mate** [comment]
@kohta-okishima 
細かいグラフデザインの反映作業はScope Outにしたので、
・円グラフの真ん中の合計数は表示しないにしましょう
・グラフカラー（RGB）はスタイルのテンプレートに合わせてください

「一般ユーザー」という表記はこちらの誤記です。「サポーター」でお願いします

**Comment by kohta-okishima** [comment]
@freecle-mate 

実装終わりましてステージングにデプロイしました。

注釈として以下申し上げます。

----------

> ・グラフカラー（RGB）はスタイルのテンプレートに合わせてください

グラフは全般的に配色の設定をしていませんのでライブラリのテンプレートでの既定値が適用されています。
ライブラリの機能で設定により任意の配色を行うこと自体は可能(容易に可能)なので貴社で適宜お願いします。

Google Analytics アカウント に関して:

アカウントやAPIの認証情報自体がないですし、そもそもデータが入っていないものだとモックベースの実装しかできないので止むを得ず個人で保持しているものを利用しました。
動作確認も実際にデータが入ってるものじゃないとできないのでステージングでのみこちらのアカウントを接続しましたが、これに関しては検収後に接続を解除させていただきますのでご了承ください。
アカウントが設定されていない場合もGoogle Analytics関連のグラフでのみエラーメッセージが表示されるだけでダッシュボード自体へはアクセスできるようにはしてあります。

アカウント自体Googleから発行されるjson形式の認証用のファイルを配置し、設定ファイルでそのファイルへのパスとview_id 指定するだけで切り替えられますますがWikiにでも設定手順や参考資料を残しておきますので貴社でアカウント取得した段階で適宜設定してください。
(Googleが用意しているものなのでわかりやすいUIで設定できますし特に複雑な手順はなく簡単です)

平均滞在時間のグラフについて:

Google Analyticsでの尺度は秒なのでグラフの単位もそれに合わせてます。

受入テストに関して:

この機能に関しては特に、グラフの数(実装が必要なモジュールやエンドポイント自体の数)の多さと各々多岐パラメータによる分岐の多さで見積もりと実施の実装ボリュームの乖離が莫大なものになっており、実際に予想より多く実装に時間がかかってしまっているので戻り修正は数値の誤りなど本質的なバグのみでお願いします。
それ以外の諸調整やKPIの変更などはご遠慮いただきますようおねがいします。

----------

動作確認実施して頂いて構いませんので宜しくお願い致します。

**Comment by freecle-mate** [comment]
@kohta-okishima 
ありがとうございます。確認しました。

ユーザー登録数とサポーター登録数も他の折れ線グラフの縦軸と同様に、
小数点表示を削除してください（＝小数点一桁・二桁の表示は必要ありません）

その他については問題ありませんので、
本件、Doneにしましょう。

**Comment by kohta-okishima** [comment]
@freecle-mate 

>ユーザー登録数とサポーター登録数も他の折れ線グラフの縦軸と同様に、
>小数点表示を削除してください（＝小数点一桁・二桁の表示は必要ありません）

この点に関してご相談させてください。

調査したところリポジトリのissueにアップされてる方法でできそうだったんですが、解決できませんでした。

>Found the solution. Just add library: {yAxis: {allowDecimals: false }}
>cite: ttps://github.com/ankane/chartkick/issues/269

なぜかと思いソースコード見たらこのオプション自体が存在していなかったです。

調査元: https://staging-www.mate-cute.com/assets/chartkick-6100bb88cb33c05c5f9c7fb7b6a229578807010662a0acf875394933ac6c338e.js
※デプロイしたら消える可能性あり

ただ、見たのはJavaScript側のソースコードで、上記リポジトリではサーバサイドでグラフを出力するヘルパーを実装したいわば拡張版のようなライブラリなので、そこ独自のオプションなのかもしれません。
今回は負荷削減のため各々のグラフを非同期で生成するようにしているため、グラフの生成はフロントエンド(JavaScript)で完結させておりサーバサイドのヘルパーは使っていないです。

小数点で表示されているのはこちらで小数という単位で指定しているわけではなく、グラフ中の値の最大値が1や2など極端に小さい数値の場合ライブラリが自動で調整を行ったいるためであり、今後データが入ってくると自然に解決しそうな問題であるためこの制御の実装を割愛できないでしょうか？

<img width="1275" alt="2017-12-23 9 50 51" src="https://user-images.githubusercontent.com/1265649/34315686-deb52022-e7c6-11e7-8a4e-5d0f1573e298.png">

どうしても1や2などの数値でy軸の小数点表示をやめたいというのであれば何か考えようとは思ってますが、グラフのレイアウト自体崩れそうな気もしますし、お手数ですが上記踏まえ一旦貴社にて再度対応必要かどうかの判断をお願いいたします。

**Comment by freecle-mate** [comment]
@kohta-okishima 
ありがとうございます。
調査していただいた内容、確認しました。

>>小数点で表示されているのはこちらで小数という単位で指定しているわけではなく、
>>グラフ中の値の最大値が1や2など極端に小さい数値の場合ライブラリが自動で調整を行ったいるため

上記、了解しました。
本件Doneにしましょう。

**Comment by kohta-okishima** [comment]
@freecle-mate 

ご確認ありがとうございます。
本イシューをクローズします。
