### ISSUE TITLE
質問・サポーター依頼画面の一部情報見直し

### ISSUE THREAD

**Issue by freecle-mate** [freecle-mate/mate#59]
@kohta-okishima 
以下、微修正をお願いします。

■運営会社の連絡先の情報変更
info@freecle.com を freecle.mate@gmail.com に変更してください。
問い合わせ先のメールアドレスを変更しました。

■質問回答後の画面の情報変更
(アプリリースは2017年12月を予定しています) という文言を削除してください。
12月リリースはできないので、消してください。

**Comment by kohta-okishima** [comment]
今回は承りますがSlackでもお送りしたように今後は検収された機能での改修依頼はご遠慮いただくようお願いします。
本件は非常に軽微な修正ですが工数は置いておいて、こちらとしては下記コメントにあるように今までの経緯から際限なく対応事項が増えることを危惧しています。

https://github.com/freecle-mate/mate/issues/52#issuecomment-351692140

**Comment by freecle-mate** [comment]
@kohta-okishima 
承知いたしました。

**Comment by kohta-okishima** [comment]
@freecle-mate 

本件対応してステージングにデプロイしました。

**Comment by freecle-mate** [comment]
@kohta-okishima 
ありがとうございます。
質問依頼画面については、問題ございません。
メールアドレス、最後の画面の表記が変わっていることを確認しました。

一点、確認させてください。
上記を本番環境にデプロイすると、
以下リンク（mateのサービス紹介画面）のメールアドレスも切り替わりますか？
https://www.mate-cute.com/supporter
サポーター依頼する際に利用している画面です。

**Comment by kohta-okishima** [comment]
@freecle-mate 

> 上記を本番環境にデプロイすると、
> 以下リンク（mateのサービス紹介画面）のメールアドレスも切り替わりますか？
> https://www.mate-cute.com/supporter

そういえば本番デプロイがまだでしたね。
本番でも切り替わるかと思います。

**Comment by freecle-mate** [comment]
🙆‍♂️

**Comment by kohta-okishima** [comment]
@freecle-mate 

本番デプロイ実行しておきました。

**Comment by freecle-mate** [comment]
確認しました。問題ありません。
本件、Doneにしましょう。

**Comment by kohta-okishima** [comment]
@freecle-mate 

ご確認ありがとうございました。
