### ISSUE TITLE
コンテンツリストの検索フォームでselect2適用させるとテキストボックス内でEnterできなくなる

### ISSUE THREAD

**Issue by kohta-okishima** [freecle-mate/mate#6]
## キャプチャ

<img width="1273" alt="2017-12-02 17 17 11" src="https://user-images.githubusercontent.com/1265649/33513383-04de5e1e-d785-11e7-8fdc-3912df3d0253.png">

仕方がないので現状は、検索コアロジックが動作しているかどうか最低限確認するため下図のようにしている

<img width="1277" alt="2017-12-02 17 03 28" src="https://user-images.githubusercontent.com/1265649/33513391-2d713220-d785-11e7-8fe5-976f5970ef2d.png">

**Comment by hori-imuuzak** [comment]
内容が上手く汲み取れていないので、12/10MTGで確認させてください

**Comment by kohta-okishima** [comment]
>コンテンツリストの検索フォームでselect2適用させるとテキストボックス内でEnterできなくなる

これより小さな粒度で説明すると時間が無駄になるのでこちらで対応することにしました。

**Comment by kohta-okishima** [comment]
#7 にてテキストボックス内でEnterできるようにしたのでクローズ。
