### ISSUE TITLE
バッチ処理仕様確認

### ISSUE THREAD

**Issue by kohta-okishima** [freecle-mate/mate#61]
下記の実装が完了しました。

```
質問に対して1ヶ月間回答がない場合、ファイルサーバからデータ削除／リンク破棄

URL短縮ロジックの有効期限設定（1ヶ月）
```

**Comment by kohta-okishima** [comment]
@freecle-mate 

掲題の件に関しまして細かい点をいくつか確認させていただきたいです。

> 質問に対して1ヶ月間回答がない場合、ファイルサーバからデータ削除／リンク破棄

有効期限ですが、具体的には管理画面の質問フォームのリンク発行ボタンを押した時点から1カ月です。
このアクションを契機として質問のエンティティが リンク発行済み ステータスになるので1カ月以上そのステータスのデータは削除されます。

実績の質問依頼数の数は変えてしまってはいけない気がしたのでそれはそのまま維持するようにしましたが、減らしてしまっていいのであれば直しますのでお申し付けください。

リンク破棄という部分に関しては、短縮する前のリンクは無効になります。
短縮URL自体は、質問とのリレーションを保持していない(それが疎結合を保つ意味で詳細設計上好ましい)ので質問データ削除バッチの実行でリンクが破棄されるわけではなく、

> URL短縮ロジックの有効期限設定（1ヶ月）

上記処理を実行するバッチで破棄されるということになっています。
ただ、そもそも削除された質問にアクセスしたら404になり、これは破棄された短縮URLにアクセスした時と同じ挙動ですのでそこまで気にする必要はないと思います。

これらいずれもバッチ処理なので定期実行する仕組みが必要ですが(cronと呼ばれるものへのスケジューリング必要)、コード化してデプロイ時に設定されるようになっています。
毎時間実行するバッチが出てきたりサービスがスケールして負荷が高くなったりしたら独立したバッチサーバを立てるというのもありだと思いますが、今回は負荷の心配もないということで費用を抑えるためにアプリサーバと同じサーバでバッチも動作させています。

実行日時は一旦 AM3:00, 4:00 あたりにデイリーでセットしておきましたが問題あれば修正します。

本件に関しましてはバッチ処理になりますので

1. こちらでバッチの処理対象となるデータを作る
2. スケジューリングされたバッチで実際に処理されるか確認する

という手順で確認し、結果を貴社に報告します。

仕様の調整が必要なところがあればお申し付けください。

**Comment by freecle-mate** [comment]
@kohta-okishima 
確認しました。問題ないです。
本件、Doneにしましょう。

**Comment by freecle-mate** [comment]
@kohta-okishima 
本件、Doneにしましょう！

**Comment by kohta-okishima** [comment]
@freecle-mate 
ご確認ありがとうございました。クローズします。
