### ISSUE TITLE
コンテンツ編集仕様確認

### ISSUE THREAD

**Issue by kohta-okishima** [freecle-mate/mate#8]
※以下実装とメンタルモデル合わせるためコンテンツのことを記事と表記

## MTG(関口さん)で決まったこと

* 記事と広告の対応は1:1
* 広告を新しくしたらクリック数をリセット
  * この場合でも古い広告のクリックログは残す
* 同じ広告でURLだけちょっと変わるなどの場合リセットしたくない

## こちらが行う予定の対応

新しい広告の作成(= クリック数リセット)と既存の編集(=クリック数リセットしない)の区別が必要
通常フォームを分けるなどするが、(UIには文句ないが)今回フォームは単一なので以下の方法で新規作成と編集の二役を持たせる

* 広告削除ボタンを設ける(右上にxボタン)
  * 押したら広告を削除(広告関連のフォームは全部空になる)
  * 広告を削除したら記事を公開できないので記事のステータスを「非公開」へ遷移させる
* 削除せずに「更新」おしたら広告のエンティティは既存のものを踏襲し、クリック数もリセットしない

ステータスに関しては下記参照
https://github.com/freecle-mate/mate/wiki/%E6%8A%95%E7%A8%BF

**Comment by kohta-okishima** [comment]
# @freecle-mate にご確認いただきたいこと

- [ ] こちらで勝手に作ってしまったので上記の基本設計のレビューをお願いします

**Comment by freecle-mate** [comment]
>>記事と広告の対応は1:1

→その通りです。

>>広告を新しくしたらクリック数をリセット
 
→2つのパターンがあります。
　①リンクを編集して新しくした場合は、古い広告のクリック数も残します。
　　ex. Amazonのリンクがリニューアル。再度、Amazonで同一商品を検索し、新しいリンクに修正
　②広告自体をリセットして、新しくする場合は、クリック数もリセットします。
　　ex. Amazonから商品・サービスがなくなる。楽天で同一商品を検索し、新しいリンクに修正

**Comment by kohta-okishima** [comment]
やりたいことはわかりましたし僕の構想で実現できそうなのでこのまま進めます。

アフィリエイトっていう仕組みってご存知ですかね？
このケースだとAmazonや楽天がアフィリエイトサービスプロバイダーですがその画面で広告のクリック数自体は取れるのですがそちらと数字の齟齬がでる可能性があることをご了承ください。

理由はプロバイダ側の計数基準をこちらで知ることはできないからです。
例えばクッキーが競合しているユーザの計数、特殊なクライアントからのクリックなど向こうはカウントしないですがこっちは特に気にせずリクエストあったらカウントしちゃうのでその辺はご了承おねがいします。

**Comment by freecle-mate** [comment]
確認ありがとうございます。

>>やりたいことはわかりましたし僕の構想で実現できそうなのでこのまま進めます。

→宜しくお願い致します。

>>このケースだとAmazonや楽天がアフィリエイトサービスプロバイダーですがその画面で広告のクリック数自体は取れるのですがそちらと数字の齟齬がでる可能性があることをご了承ください。

→はい、認識した上でお願いしています。こちらの説明不足でした。

**Comment by freecle-mate** [comment]
→×ボタンだと記事が削除されると誤認識してしまうので、広告リセットボタンをつくる リセットの場合は新規の広告、リンクを打ち直す場合は更新というフローにする（prott更新予定）
こちらのprott更新しました
https://prottapp.com/p/b847c9

**Comment by kohta-okishima** [comment]
🙆‍♂️

**Comment by kohta-okishima** [comment]
ref: https://github.com/freecle-mate/mate/issues/38
