### ISSUE TITLE
お知らせ機能の要件

### ISSUE THREAD

**Issue by kohta-okishima** [freecle-mate/mate#9]
## 要件

？(以下こちらの解釈です)

* 掲載OK以降のステータスの投稿(要するに質問に回答いただいた投稿)がInstagramでのページがなくなっていた場合(コンテンツの元本がなくなっていた場合)にお知らせする
* 記事を非公開にする
* ファイルサーバに保存してある画像を削除する

ステータスに関しては下記を参考
https://github.com/freecle-mate/mate/wiki/%E6%8A%95%E7%A8%BF

## キャプチャ

<img width="1275" alt="2017-12-02 18 08 25" src="https://user-images.githubusercontent.com/1265649/33513732-0f3a3f70-d78c-11e7-9051-deb8c86b4b81.png">

※prottのURLがうまく貼れない(1スライド目に移動する)のでキャプチャを貼った

**Comment by kohta-okishima** [comment]
# @freecle-mate へご確認いただきたいこと

- [] 要件の解釈は間違ってないでしょうか？
- [] このケースで削除した記事は物理削除でよろしいでしょうか？それとも「リンク切れ」というステータスみたいなの作って論理削除に近い制御にしたほうがよろしいでしょうか？
- [] バッチはどれぐらいの頻度で走らせればよろしいでしょうか？
- [] 「リンク切れのサイトがあります。」をクリックした場合の制御を教えてください
- [] もともとスコープになかった機能というのもありますが実装コストがかなり大きいものであるため対応フェーズの相談をさせてください

**Comment by freecle-mate** [comment]
>>要件の解釈は間違ってないでしょうか？
元々、私たちが想定している「お知らせ機能」とは、Instagramの画像・動画がなくなったことの通知ではなく、広告リンクのアクセス不可です。
Instagramの画像・動画はmateのファイルサーバ上で保管している為、Instagram上で画像・動画がなくなったとしても、mate上にはのこせると考えていましたが、この認識間違えていますか？

もしInstagramの画像・動画がなくなった場合、mate上からも消えてしまう場合は、
「お知らせ機能」に2種類の通知を行う必要があります。

①広告リンクアクセス不可の場合
　↳リンク切れのアフィリエイトを多用すると、楽天・Amazonからアフィリエイト企業として不適切
　　とみなされ、利用停止になるリスクがある為、この機能の実装を検討しています。
　　　↳リンク切れが通知された場合の運用オペレーション
　　　　　- 別の商品・サービス紹介サイトを探し、リンクを変更する
　　　　　- 商品・サービス自体の販売が停止されている場合は、論理削除する
　　　↳リンク切れが発生した場合のアプリ画面遷移
　　　　　- HTTP エラー 403表示

②Instagram画像・動画利用不可の場合
　↳サポーターが何らかの理由でアカウントを削除した場合、データが消失する為、
　　この機能の実装が必要になる（freecle想定外のケース／沖島さんの懸念点）
　　　↳リンク切れが通知された場合の運用オペレーション
　　　　　- 物理削除する
　　　↳リンク切れが発生した場合のアプリ画面遷移
　　　　　- 自動的にアプリ上から消失する

**Comment by freecle-mate** [comment]
>>バッチはどれぐらいの頻度で走らせればよろしいでしょうか？
　↳１時間おきでおねがいします。

>>「リンク切れのサイトがあります。」をクリックした場合の制御を教えてください
　↳リンク切れのコンテンツ編集画面に飛びます。広告のサムネイルとリンクが消えてる状態で表示され編集・更新できる。 また、編集画面に削除ボタンを用意し、削除できるようにする。（prottを更新予定）

>>もともとスコープになかった機能というのもありますが実装コストがかなり大きいものであるため対応フェーズの相談をさせてください
　↳承知致しました。
　　上記の回答をご確認いただき、改めて実装コストがかなり大きいと思われますか？
　　改めて見解を教えて下さい。

**Comment by kohta-okishima** [comment]
>元々、私たちが想定している「お知らせ機能」とは、Instagramの画像・動画がなくなったことの通知ではなく、広告リンクのアクセス不可です。

これ、さっき別のイシューで関連すること言及しましたがリンク切れの基準が広告のプロバイダによって違うのでまず調査から必要ですし、用いるプロバイダの数に比例して実装コストかかります。

例えばあるプロバイダは404を返さない。別のページへリダイレクト(ステータスは302だったかな？)など仕様がまちまちなので。
質のいいAP Iあれば多少楽ですが問題の本質は変わらないかと。

>上記の回答をご確認いただき、改めて実装コストがかなり大きいと思われますか？
>　　改めて見解を教えて下さい。

ので、場合によりますがかなり重いです。

単に広告のクリック切れ確認したいならプロバイダの管理画面に確実についてるのでそっち使った方がいいかもしれません。その辺の判断はお任せします。

>Instagramの画像・動画はmateのファイルサーバ上で保管している為、Instagram上で画像・動画がなくなったとしても、mate上には残せるはずと考えていましたが、この認識間違えていますか？

間違ってないです。
御社の法務部が問題ないという判断なら僕は関知することではないので残しておく方向で進めます。というより今そうなってます。

>それ程、サーバに負荷は掛からないと予想しています。どう思われますか？

広告の数によります。頻度は処理対象数との兼ね合いみて決めることになると思いますが最初は数も少ないので時間毎で問題ないように思います。

ただこれも仮にAmazonへのリンクが10000件とかあって、無効のサーバがこっちのバッチサーバからのアクセスを禁止したら機能自体が使えなくなるのでその辺をご了承いただければ幸いです。なお、可能性としては低いです。

**Comment by kohta-okishima** [comment]
スコープアウトされる機能なのでクローズ
